site_name: VERONA Docs


theme:
  name: "material"

plugins:
  - mkdocstrings
  - search:
      lang: en

nav:
  - index.md
  - how-to-guides.md
  - api.md
  - pytorch_support.md


repo_url: https://github.com/ADA-research/VERONA/
repo_name: ADA-VERONA


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list