name: Lint Python Code

on:
  pull_request:
    branches: [main]  # Adjust this to the branch you want to lint on PRs
  push:
    branches: [main]  # Adjust this to the branch you want to lint on pushes

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 robustness_experiment_box tests  # Replace 'your_module' with the name of your Python module
